#!/usr/bin/env python
"""
Sounddrizzle - a tiny Soundcloud downloader.

Usage:
    sounddrizzle.py [options] <url> [<output>]

Options:
    --output <FILE> 			The output file (defaults to artist/title)
    -v. --verbose                   More output!
    -q, --quiet
"""
import logging

from sounddrizzle import pour
from docopt import docopt


def main(args):
    setup_logging(args)
    pour(args['<url>'], args['<output>'])


def setup_logging(args):
    logging.basicConfig(format='%(asctime)s [%(levelname)s] %(msg)s')

    if args['--quiet']:
        loglevel = logging.ERROR
    elif args['--verbose']:
        loglevel = logging.DEBUG
    else:
        loglevel = logging.INFO

    logging.getLogger('SoundDrizzle').setLevel(loglevel)


if __name__ == '__main__':
    args = docopt(__doc__)
    main(args)
